# Generated by Django 4.2.4 on 2023-09-23 11:31

import django.core.validators
from django.db import migrations, models
import django_bleach.models
import logic.models_validators


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[logic.models_validators.validate_photo_ext], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='text',
            field=django_bleach.models.BleachField(max_length=4096, validators=[django.core.validators.MaxLengthValidator(limit_value=102400, message='Restriction 100 KB'), logic.models_validators.validate_html_tags, logic.models_validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
