# Generated by Django 4.2.4 on 2023-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_recordfields_txt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfields',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='userfields',
            name='photo',
        ),
        migrations.AlterField(
            model_name='recordfields',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
